### ISSUE TITLE
Load workspace from config file

### ISSUE THREAD

**Issue by rafaelrozon** [eBayClassifiedsGroup/update-ts-references#31]
Hello,

First of all, thanks for writing this library. I would like to use it in a project that is managed by [Rush](https://rushjs.io/). The project doesn't contain a lerna.json or pnpm-workspaces.yml file. Would you be open to adding an additional option to load workspace configuration from a `.update-ts-references.config.js` file, or something like that, using [cosmicconfig](https://www.npmjs.com/package/cosmiconfig). 

If you're ok with that, I can put a PR together. 

thanks!

**Comment by MKruschke** [comment]
Hi @rafaelrozon,
thanks for reaching out and yes this sounds reasonable to me. What do you think about the PR #34 would that work for you?

**Comment by rafaelrozon** [comment]
Yes, that works great. Thanks a lot for making the changes. 

I'm now facing a different issue. I can create a new PR if you think it's a good idea to support it. I work on a project with multiple packages and kinds of Typescript config files. Some are used only for type checking in  pipelines, others are used to exclude certain folders from the distributed files. What happens is that: 1) I have to use the update-ts-reference.yaml file because I'm using Rush, and 2) that file supports a single configuration set. There's no way for me to update the references for, let's say, `tsconfig.json` and tsconfig.typecheck.json` files.

I could generate that file on the fly or do some processing before run. But it would be nice if the library supported this. 

A couple of approaches I can think of:
1) the yaml supports multiple configuration
2) all the options are supported via CLI so users can run the library with different options for different use cases

Again, happy to help.

**Comment by MKruschke** [comment]
Hi @rafaelrozon, 
did you tried to use `extends` (since a few versions you can add multiple files there) and move the project references to a dedicated file? But in general the idea/use-case would be fine for me esp if you want to configure different paths. 

Ok let's talk about the options:

> all the options are supported via CLI so users can run the library with different options for different use cases. 

not my favourite here because of readability esp with the paths that you want to pass as array 😅 Alternatively we could think about pointing to a specific config filename via the _cli_ so you can have multiple configs in your project. _update-ts-references.yaml_ for the main use-case and _update-ts-references-typecheck.yaml_ for the other.

>  the yaml supports multiple configuration

what do you think about some overwrites via a cli param you can choose which one you want to execute `npx update-ts-references --use-config typecheck-usecase` see below how the config could look like?
```yaml
configName: 'tsconfig.json'
rootConfigName: 'tsconfig.json'
createPathMappings: true
packages:
  - 'apps/**'
  # exclude packages that are inside test directories
  - '!**/tests/**'
  - '!workspace-ignore'
overwrites:
  - typecheck-usecase:
    configName: 'tsconfig.typecheck.json'
    rootConfigName: 'tsconfig.typecheck.json'
  - cypress-e2e-usecase:
    configName: 'tsconfig.cy.json'
    rootConfigName: 'tsconfig.cy.json'
    packages:
      - 'e2e/**'
 
```
